language: node_js
node_js:
  - "10"
script:
  - npm run build
  - npm run deploy
deploy:
  provider: pages
  github_token: d0f272b327f005e43003c8b785122bf12c45e0ff
  skip_cleanup: true
  on:
    branch: master
  fqdn: dev.elhamnaseri.com