language: node_js
node_js:
  - "10"
script:
  - npm run build
  - npm run deploy
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master
  fqdn: dev.elhamnaseri.com